import type { TrainingDetail, TrainingQuizUi } from "./types";

const quizUi: TrainingQuizUi = {
  title: {
    uk: "Перевірка знань",
    en: "Knowledge check",
    de: "Wissenscheck",
    es: "Comprobación de conocimientos",
    fr: "Contrôle des connaissances",
    az: "Bilik yoxlaması",
    kk: "Білім тексерісі",
  },
  submit: {
    uk: "Перевірити відповіді",
    en: "Check answers",
    de: "Antworten prüfen",
    es: "Comprobar respuestas",
    fr: "Vérifier les réponses",
    az: "Cavabları yoxla",
    kk: "Жауаптарды тексеру",
  },
  reset: {
    uk: "Спробувати ще раз",
    en: "Try again",
    de: "Erneut versuchen",
    es: "Intentar de nuevo",
    fr: "Réessayer",
    az: "Yenidən cəhd edin",
    kk: "Қайта көру",
  },
  incomplete: {
    uk: "Оберіть відповідь на кожне запитання, щоб перевірити результат.",
    en: "Select an answer for every question to check your result.",
    de: "Wählen Sie für jede Frage eine Antwort, um Ihr Ergebnis zu prüfen.",
    es: "Seleccione una respuesta para cada pregunta para comprobar su resultado.",
    fr: "Sélectionnez une réponse pour chaque question afin de vérifier votre résultat.",
    az: "Nəticəni yoxlamaq üçün hər suala cavab seçin.",
    kk: "Нәтижені тексеру үшін әр сұраққа жауап таңдаңыз.",
  },
  scoreLabel: {
    uk: "Результат: {score} з {total}",
    en: "Score: {score} of {total}",
    de: "Ergebnis: {score} von {total}",
    es: "Resultado: {score} de {total}",
    fr: "Score : {score} sur {total}",
    az: "Nəticə: {score} / {total}",
    kk: "Нәтиже: {score} / {total}",
  },
  correctLabel: {
    uk: "Правильно",
    en: "Correct",
    de: "Richtig",
    es: "Correcto",
    fr: "Correct",
    az: "Düzgün",
    kk: "Дұрыс",
  },
  wrongLabel: {
    uk: "Неправильно",
    en: "Incorrect",
    de: "Falsch",
    es: "Incorrecto",
    fr: "Incorrect",
    az: "Yanlış",
    kk: "Қате",
  },
};

/** RU: Тренінг «Дії під час атак БПЛА». EN: UAV-attacks training with quiz. */
export const uavAttacksTraining: TrainingDetail = {
  slug: "uav-attacks",
  href: "/education/trainings/uav-attacks",
  /** Client request: temporarily disable this training on the public site. */
  published: false,
  title: {
    uk: "Дії під час атак БПЛА",
    en: "Actions during UAV attacks",
    de: "Verhalten bei UAV-Angriffen",
    es: "Actuación durante ataques con UAV",
    fr: "Conduite à tenir lors d’attaques par UAV",
    az: "PİA hücumları zamanı hərəkətlər",
    kk: "UAV шабуылдары кезіндегі әрекеттер",
  },
  summary: {
    uk: "Відеотренінг про безпечні дії цивільних під час атак безпілотників, з перевіркою знань після перегляду.",
    en: "A video training on civilian safety actions during UAV attacks, with a knowledge check after watching.",
    de: "Videoschulung zu sicherem Verhalten von Zivilpersonen bei Drohnenangriffen, mit Wissenscheck nach dem Anschauen.",
    es: "Formación en vídeo sobre actuaciones de seguridad de civiles durante ataques con drones, con comprobación de conocimientos tras el visionado.",
    fr: "Formation vidéo sur les actions de sécurité des civils lors d’attaques de drones, avec contrôle des connaissances après le visionnage.",
    az: "PİA (drones) hücumları zamanı mülki şəxslərin təhlükəsiz hərəkətləri üzrə video təlim, baxışdan sonra bilik yoxlaması ilə.",
    kk: "Ұшқышсыз ұшақтар шабуылы кезінде бейбіт тұрғындардың қауіпсіз әрекеттері бойынша бейне тренинг, қарағаннан кейін білім тексерісімен.",
  },
  courseCode: "UAV",
  duration: {
    uk: "10 хвилин",
    en: "10 minutes",
  },
  certificateTitles: {
    uk: "ДІЇ ПІД ЧАС АТАК БПЛА",
    en: "ACTIONS DURING UAV ATTACKS",
  },
  /** Static PDF kept as legacy fallback reference; named generator is primary when courseCode is set. */
  certificateDocId: "trainings/uav-attacks-certificate",
  passThresholdPercent: 80,
  quizUi,
  modules: [
    {
      id: "main",
      title: {
        uk: "Модуль 1",
        en: "Module 1",
        de: "Modul 1",
        es: "Módulo 1",
        fr: "Module 1",
        az: "Modul 1",
        kk: "1-модуль",
      },
      videoTitle: {
        uk: "Відео: Дії під час атак БПЛА",
        en: "Video: Actions during UAV attacks",
        de: "Video: Verhalten bei UAV-Angriffen",
        es: "Vídeo: Actuación durante ataques con UAV",
        fr: "Vidéo : Conduite à tenir lors d’attaques par UAV",
        az: "Video: PİA hücumları zamanı hərəkətlər",
        kk: "Бейне: UAV шабуылдары кезіндегі әрекеттер",
      },
      youtubeId: "7k3REZ12lpo",
      quiz: [
        {
          id: 1,
          question: {
            uk: "Яка тактична ознака названа головною відмінністю FPV-дрона від ударного камікадзе типу «Шахед»?",
            en: "Which tactical feature is named as the main difference between an FPV drone and a Shahed-type kamikaze strike UAV?",
            de: "Welches taktische Merkmal wird als Hauptunterschied zwischen einer FPV-Drohne und einer Shahed-Kamikaze-Angriffsdrohne genannt?",
            es: "¿Qué característica táctica se señala como la principal diferencia entre un dron FPV y un UAV kamikaze de tipo Shahed?",
            fr: "Quelle caractéristique tactique est présentée comme la principale différence entre un drone FPV et un UAV kamikaze de type Shahed ?",
            az: "FPV dronu ilə «Şahed» tipli kamikadze zərbə PİA-sı arasındakı əsas fərq kimi hansı taktik əlamət göstərilir?",
            kk: "FPV дрон мен «Шахед» типті камикадзе соққы UAV арасындағы негізгі айырмашылық ретінде қандай тактикалық белгі аталады?",
          },
          options: {
            A: {
              uk: "Наявність живого оператора, який прицільно шукає рухомі об'єкти",
              en: "A live operator who deliberately searches for moving targets",
              de: "Ein Live-Operator, der gezielt nach beweglichen Zielen sucht",
              es: "Un operador en vivo que busca deliberadamente objetivos en movimiento",
              fr: "Un opérateur en direct qui recherche délibérément des cibles mobiles",
              az: "Hərəkət edən hədəfləri məqsədyönlü axtaran canlı operator",
              kk: "Қозғалмалы нысандарды мақсатты іздейтін тірі оператор",
            },
            B: {
              uk: "Здатність рухатися на гранично малих висотах вздовж міських вулиць",
              en: "The ability to fly at extremely low altitude along city streets",
              de: "Die Fähigkeit, in extrem geringer Höhe entlang von Stadtstraßen zu fliegen",
              es: "La capacidad de volar a altitud extremadamente baja por calles urbanas",
              fr: "La capacité de voler à très basse altitude le long des rues urbaines",
              az: "Şəhər küçələri boyunca çox aşağı hündürlükdə uçmaq qabiliyyəti",
              kk: "Қала көшелері бойымен өте төмен биіктікте ұшу қабілеті",
            },
            C: {
              uk: "Застосування виключно осколкової бойової частини спрямованої дії",
              en: "Use of an exclusively fragmentation warhead with directed effect",
              de: "Einsatz ausschließlich eines Splittergefechtskopfs mit gerichteter Wirkung",
              es: "Uso exclusivo de una ojiva de fragmentación de efecto dirigido",
              fr: "Utilisation exclusive d’une charge à fragmentation à effet dirigé",
              az: "Yalnız yönəldilmiş təsirli qəlpəli döyüş hissəsinin tətbiqi",
              kk: "Тек бағытталған әсерлі сынықтық ұрыс бөлігін қолдану",
            },
          },
          correct: "A",
        },
        {
          id: 2,
          question: {
            uk: "Яку дихальну техніку рекомендовано застосовувати для фізіологічного зниження частоти пульсу?",
            en: "Which breathing technique is recommended to physiologically lower the pulse rate?",
            de: "Welche Atemtechnik wird empfohlen, um die Pulsfrequenz physiologisch zu senken?",
            es: "¿Qué técnica de respiración se recomienda para bajar fisiológicamente la frecuencia del pulso?",
            fr: "Quelle technique respiratoire est recommandée pour abaisser physiologiquement la fréquence du pouls ?",
            az: "Nəbz tezliyini fizioloji olaraq azaltmaq üçün hansı nəfəs texnikası tövsiyə olunur?",
            kk: "Пульс жиілігін физиологиялық төмендету үшін қандай тыныс алу әдісі ұсынылады?",
          },
          options: {
            A: {
              uk: "Затримку дихання на вісім секунд одразу після глибокого видиху",
              en: "Holding the breath for eight seconds right after a deep exhale",
              de: "Den Atem acht Sekunden lang direkt nach einem tiefen Ausatmen anhalten",
              es: "Contener la respiración ocho segundos justo después de una exhalación profunda",
              fr: "Retenir sa respiration pendant huit secondes juste après une expiration profonde",
              az: "Dərin nəfəsvermədən dərhal sonra səkkiz saniyə nəfəsi saxlamaq",
              kk: "Терең дем шығарғаннан кейін бірден сегіз секунд демді ұстап тұру",
            },
            B: {
              uk: "Повільний вдих на три рахунки та подовжений видих на шість рахунків",
              en: "A slow inhale for a count of three and a prolonged exhale for a count of six",
              de: "Langsam einatmen auf drei und verlängert ausatmen auf sechs",
              es: "Inhalación lenta contando hasta tres y exhalación prolongada contando hasta seis",
              fr: "Une inspiration lente sur un compte de trois et une expiration prolongée sur un compte de six",
              az: "Üç hesabına yavaş nəfəsalma və altı hesabına uzadılmış nəfəsvermə",
              kk: "Үшке дейін санап баяу дем алу және алтыға дейін санап ұзақ дем шығару",
            },
            C: {
              uk: "Серію коротких інтенсивних вдихів через ніс протягом однієї хвилини",
              en: "A series of short intense nasal inhales for one minute",
              de: "Eine Serie kurzer intensiver Naseneinatmungen über eine Minute",
              es: "Una serie de inhalaciones nasales cortas e intensas durante un minuto",
              fr: "Une série d’inspirations nasales courtes et intenses pendant une minute",
              az: "Bir dəqiqə ərzində burundan qısa intensiv nəfəsalmalar seriyası",
              kk: "Бір минут бойы мұрын арқылы қысқа қарқынды дем алулар сериясы",
            },
          },
          correct: "B",
        },
        {
          id: 3,
          question: {
            uk: "Яке технічне рішення для вікон блокує від 90 до 95% руйнівної енергії вибухової хвилі?",
            en: "Which window protection solution blocks 90–95% of the destructive energy of a blast wave?",
            de: "Welche Fensterschutzlösung blockiert 90–95 % der zerstörerischen Energie einer Druckwelle?",
            es: "¿Qué solución de protección de ventanas bloquea el 90–95 % de la energía destructiva de una onda expansiva?",
            fr: "Quelle solution de protection des fenêtres bloque 90 à 95 % de l’énergie destructrice d’une onde de choc ?",
            az: "Pəncərələr üçün hansı texniki həll partlayış dalğasının dağıdıcı enerjisinin 90–95%-ni bloklayır?",
            kk: "Терезелер үшін қандай техникалық шешім жарылыс толқынының бұзушы энергиясының 90–95%-ын бөгейді?",
          },
          options: {
            A: {
              uk: "Поєднання ударостійкого скла триплекс та важких металевих ролет",
              en: "A combination of impact-resistant triplex glass and heavy metal roller shutters",
              de: "Eine Kombination aus stoßfestem Triplex-Glas und schweren Metallrollläden",
              es: "Una combinación de vidrio triplex resistente a impactos y persianas metálicas pesadas",
              fr: "Une combinaison de verre triplex résistant aux chocs et de volets roulants métalliques lourds",
              az: "Zərbəyədavamlı tripleks şüşə və ağır metal jalüzlərin birləşməsi",
              kk: "Соққыға төзімді триплекс әйнек пен ауыр металл роллеттердің үйлесімі",
            },
            B: {
              uk: "Наклеювання багатошарової малярної стрічки або армованого скотчу",
              en: "Applying multiple layers of masking tape or reinforced duct tape",
              de: "Aufkleben mehrerer Lagen Malerband oder verstärktem Gewebeband",
              es: "Aplicar varias capas de cinta de enmascarar o cinta reforzada",
              fr: "Appliquer plusieurs couches de ruban de masquage ou de ruban adhésif renforcé",
              az: "Çoxqatlı boyaçılıq lentinin və ya möhkəmləndirilmiş skotcun yapışdırılması",
              kk: "Көп қабатты малярлық таспаны немесе арматураланған скотчты жапсыру",
            },
            C: {
              uk: "Встановлення легких зовнішніх металевих ґрат проти кумуляцій",
              en: "Installing light external metal grilles against shaped charges",
              de: "Montage leichter äußerer Metallgitter gegen Hohlladungen",
              es: "Instalar rejas metálicas exteriores ligeras contra cargas huecas",
              fr: "Installer de légères grilles métalliques extérieures contre les charges creuses",
              az: "Kumulativ yüklərə qarşı yüngül xarici metal barmaqlıqların quraşdırılması",
              kk: "Кумулятивтік зарядтарға қарсы жеңіл сыртқы металл торлар орнату",
            },
          },
          correct: "A",
        },
        {
          id: 4,
          question: {
            uk: "Що згідно з інструкцією необхідно робити, якщо безпілотник уже пікірує у ваш напрямок?",
            en: "According to the guidance, what should you do if a UAV is already diving toward you?",
            de: "Was sollten Sie laut Anleitung tun, wenn eine Drohne bereits auf Sie zustürzt?",
            es: "Según las instrucciones, ¿qué debe hacer si un UAV ya se lanza en picado hacia usted?",
            fr: "Selon les consignes, que devez-vous faire si un UAV plonge déjà vers vous ?",
            az: "Təlimata görə, PİA artıq sizin istiqamətinizə dalırsa nə etməlisiniz?",
            kk: "Нұсқауға сәйкес, UAV сізге қарай шүңгіп келе жатса не істеу керек?",
          },
          options: {
            A: {
              uk: "Лягти на спину, підняти руки догори та широко відкрити очі",
              en: "Lie on your back, raise your arms, and open your eyes wide",
              de: "Auf den Rücken legen, die Arme heben und die Augen weit öffnen",
              es: "Tumbarse de espaldas, levantar los brazos y abrir bien los ojos",
              fr: "S’allonger sur le dos, lever les bras et ouvrir grand les yeux",
              az: "Bel üstə uzanmaq, əlləri yuxarı qaldırmaq və gözləri geniş açmaq",
              kk: "Арқамен жатып, қолдарыңызды көтеріп, көзді кең ашу",
            },
            B: {
              uk: "Бігти по прямій траєкторії на максимальній швидкості до дверей",
              en: "Sprint in a straight line at maximum speed toward a door",
              de: "In gerader Linie mit Höchstgeschwindigkeit zu einer Tür sprinten",
              es: "Correr en línea recta a máxima velocidad hacia una puerta",
              fr: "Sprinter en ligne droite à vitesse maximale vers une porte",
              az: "Maksimum sürətlə düz xətt üzrə qapıya qaçmaq",
              kk: "Максималды жылдамдықпен түзу сызықпен есікке қарай жүгіру",
            },
            C: {
              uk: "Здійснювати спринт змійкою, різко змінюючи вектор кожні 7-10 м",
              en: "Sprint in a zigzag, sharply changing direction every 7–10 m",
              de: "Im Zickzack sprinten und alle 7–10 m scharf die Richtung wechseln",
              es: "Correr en zigzag, cambiando bruscamente de dirección cada 7–10 m",
              fr: "Sprinter en zigzag en changeant brusquement de direction tous les 7 à 10 m",
              az: "Hər 7–10 metrdən bir istiqaməti kəskin dəyişərək ilanvari sprint etmək",
              kk: "Әр 7–10 метр сайын бағытты күрт өзгертіп, зигзагпен спринт жасау",
            },
          },
          correct: "C",
        },
        {
          id: 5,
          question: {
            uk: "Яке положення тіла слід прийняти пішоходу під час неминучого скиду вибухівки або вибуху?",
            en: "What body position should a pedestrian take during an imminent explosive drop or blast?",
            de: "Welche Körperhaltung sollte ein Fußgänger bei einem bevorstehenden Sprengabwurf oder einer Explosion einnehmen?",
            es: "¿Qué posición corporal debe adoptar un peatón ante una caída inminente de explosivo o una explosión?",
            fr: "Quelle position corporelle un piéton doit-il adopter en cas de largage explosif imminent ou d’explosion ?",
            az: "Yaxınlaşan partlayıcı atılması və ya partlayış zamanı piyada hansı bədən vəziyyətini tutmalıdır?",
            kk: "Жақындап келе жатқан жарылғыш тастау немесе жарылыс кезінде жаяу жүргінші қандай дене қалпын қабылдауы керек?",
          },
          options: {
            A: {
              uk: "Впасти обличчям вниз, ноги разом у бік вибуху, відкрити свій рот",
              en: "Drop face-down, keep legs together toward the blast, and open your mouth",
              de: "Bauchlage einnehmen, Beine zusammen zur Explosion hin, Mund öffnen",
              es: "Caer boca abajo, mantener las piernas juntas hacia la explosión y abrir la boca",
              fr: "Se jeter face contre terre, jambes jointes vers l’explosion, et ouvrir la bouche",
              az: "Üzü aşağı düşmək, ayaqları partlayışa doğru birləşdirmək və ağzı açmaq",
              kk: "Бетіңізбен төмен құлап, аяқтарыңызды жарылысқа қарай біріктіріп, аузыңызды ашу",
            },
            B: {
              uk: "Лягти на бік, підтягнути ноги до живота та міцно стиснути зуби",
              en: "Lie on your side, pull your knees to your stomach, and clench your teeth",
              de: "Auf die Seite legen, Knie zum Bauch ziehen und die Zähne zusammenbeißen",
              es: "Tumbarse de lado, llevar las rodillas al abdomen y apretar los dientes",
              fr: "S’allonger sur le côté, ramener les genoux vers le ventre et serrer les dents",
              az: "Yan üstə uzanmaq, dizləri qarına çəkmək və dişləri sıxmaq",
              kk: "Қабырғамен жатып, тізелерді ішке тартып, тістерді қатты қысу",
            },
            C: {
              uk: "Сісти на коліна спиною до епіцентру й закрити вуха обома руками",
              en: "Kneel with your back to the epicenter and cover your ears with both hands",
              de: "Mit dem Rücken zum Epizentrum knien und beide Ohren mit den Händen schützen",
              es: "Arrodillarse de espaldas al epicentro y cubrirse los oídos con ambas manos",
              fr: "S’agenouiller dos à l’épicentre et se couvrir les oreilles avec les deux mains",
              az: "Episentrə arxa çevirərək diz çökmək və hər iki əllə qulaqları örtmək",
              kk: "Эпицентрге арқаны беріп тізерлеп отырып, құлақты екі қолмен жабу",
            },
          },
          correct: "A",
        },
        {
          id: 6,
          question: {
            uk: "Який протокол дій визначено для цивільного автомобіля у разі виявлення атаки ворожого БПЛА?",
            en: "What action protocol is defined for a civilian car if a hostile UAV attack is detected?",
            de: "Welches Handlungsprotokoll gilt für ein ziviles Auto bei Erkennung eines feindlichen UAV-Angriffs?",
            es: "¿Qué protocolo de actuación se define para un coche civil si se detecta un ataque de UAV hostil?",
            fr: "Quel protocole d’action est défini pour une voiture civile en cas de détection d’une attaque par UAV hostile ?",
            az: "Düşmən PİA hücumu aşkarlandıqda mülki avtomobil üçün hansı hərəkət protokolu müəyyən edilib?",
            kk: "Жауласқан UAV шабуылы анықталғанда азаматтық автомобиль үшін қандай әрекет хаттамасы белгіленген?",
          },
          options: {
            A: {
              uk: "Збільшити швидкість до максимуму, намагаючись відірватися від дрона",
              en: "Increase speed to the maximum and try to outrun the drone",
              de: "Geschwindigkeit auf Maximum erhöhen und versuchen, der Drohne zu entkommen",
              es: "Aumentar la velocidad al máximo e intentar escapar del dron",
              fr: "Augmenter la vitesse au maximum et tenter de distancer le drone",
              az: "Sürəti maksimuma çatdırıb drondan qaçmağa çalışmaq",
              kk: "Жылдамдықты максимумға жеткізіп, дроннан қашуға тырысу",
            },
            B: {
              uk: "Зупинитися, негайно залишити салон та розбігтися у різні боки",
              en: "Stop, leave the cabin immediately, and run in different directions",
              de: "Anhalten, die Kabine sofort verlassen und in verschiedene Richtungen weglaufen",
              es: "Detenerse, abandonar el habitáculo de inmediato y correr en direcciones distintas",
              fr: "S’arrêter, quitter immédiatement l’habitacle et courir dans des directions différentes",
              az: "Dayanmaq, salonu dərhal tərk etmək və müxtəlif istiqamətlərə qaçmaq",
              kk: "Тоқтап, кабинаны дереу тастап, әртүрлі бағытқа жүгіру",
            },
            C: {
              uk: "З'їхати на узбіччя та сховатися безпосередньо під днищем машини",
              en: "Pull onto the shoulder and hide directly under the vehicle",
              de: "Auf den Seitenstreifen fahren und sich direkt unter dem Fahrzeug verstecken",
              es: "Apartarse al arcén y esconderse directamente bajo el vehículo",
              fr: "Se ranger sur l’accotement et se cacher directement sous le véhicule",
              az: "Yol kənarına çıxmaq və birbaşa avtomobilin altında gizlənmək",
              kk: "Жол жиегіне шығып, тікелей көліктің астына жасырыну",
            },
          },
          correct: "B",
        },
        {
          id: 7,
          question: {
            uk: "Які внутрішні локації житлового будинку визначено як небезпечні («червоні зони») при атаці FPV?",
            en: "Which interior locations of a residential building are defined as dangerous (“red zones”) during an FPV attack?",
            de: "Welche Innenbereiche eines Wohngebäudes gelten bei einem FPV-Angriff als gefährliche „rote Zonen“?",
            es: "¿Qué ubicaciones interiores de un edificio residencial se definen como peligrosas («zonas rojas») durante un ataque FPV?",
            fr: "Quels emplacements intérieurs d’un immeuble résidentiel sont définis comme dangereux (« zones rouges ») lors d’une attaque FPV ?",
            az: "FPV hücumu zamanı yaşayış binasının hansı daxili məkanları təhlükəli («qırmızı zonalar») hesab olunur?",
            kk: "FPV шабуылы кезінде тұрғын үйдің қандай ішкі орындары қауіпті («қызыл аймақтар») деп анықталған?",
          },
          options: {
            A: {
              uk: "Ванні кімнати та повністю ізольовані коридори без будь-яких вікон",
              en: "Bathrooms and fully enclosed corridors without any windows",
              de: "Bäder und vollständig geschlossene Flure ohne Fenster",
              es: "Baños y pasillos totalmente cerrados sin ventanas",
              fr: "Salles de bain et couloirs entièrement fermés sans fenêtres",
              az: "Hamam otaqları və heç bir pəncərəsi olmayan tam bağlı dəhlizlər",
              kk: "Жуынатын бөлмелер және терезесі жоқ толық жабық дәліздер",
            },
            B: {
              uk: "Відкриті балкони, верхні поверхи споруди та відкриті сходові клітини",
              en: "Open balconies, upper floors of the building, and open stairwells",
              de: "Offene Balkone, obere Stockwerke und offene Treppenhäuser",
              es: "Balcones abiertos, plantas superiores del edificio y cajas de escalera abiertas",
              fr: "Balcons ouverts, étages supérieurs du bâtiment et cages d’escalier ouvertes",
              az: "Açıq balkonlar, binanın yuxarı mərtəbələri və açıq pilləkən qəfəsləri",
              kk: "Ашық балкондар, ғимараттың жоғарғы қабаттары және ашық баспалдақ торлары",
            },
            C: {
              uk: "Цокольні приміщення та глибокі підвали з залізобетонним перекриттям",
              en: "Basement spaces and deep cellars with reinforced-concrete floors",
              de: "Kelleräume und tiefe Kellerräume mit Stahlbetondecken",
              es: "Espacios de sótano y bodegas profundas con forjados de hormigón armado",
              fr: "Espaces de sous-sol et caves profondes avec planchers en béton armé",
              az: "Dəmir-beton örtüklü zirzəmi məkanları və dərin yeraltı otaqlar",
              kk: "Темірбетон төбелі цоколь үй-жайлар және терең жертөлелер",
            },
          },
          correct: "B",
        },
        {
          id: 8,
          question: {
            uk: "Який проміжок часу визначено як «критичне вікно» для нанесення тактичного повторного удару?",
            en: "Which time interval is defined as the “critical window” for a tactical follow-up strike?",
            de: "Welches Zeitintervall gilt als „kritisches Fenster“ für einen taktischen Folgeangriff?",
            es: "¿Qué intervalo de tiempo se define como la «ventana crítica» para un impacto táctico de seguimiento?",
            fr: "Quel intervalle de temps est défini comme la « fenêtre critique » pour une frappe de suivi tactique ?",
            az: "Taktik təkrar zərbə üçün «kritik pəncərə» kimi hansı vaxt intervalı müəyyən edilib?",
            kk: "Тактикалық қайта соққы үшін «сындарлы терезе» деп қандай уақыт аралығы белгіленген?",
          },
          options: {
            A: {
              uk: "Інтервал тривалістю від десяти до п’ятнадцяти хвилин після атаки",
              en: "An interval of ten to fifteen minutes after the attack",
              de: "Ein Intervall von zehn bis fünfzehn Minuten nach dem Angriff",
              es: "Un intervalo de diez a quince minutos después del ataque",
              fr: "Un intervalle de dix à quinze minutes après l’attaque",
              az: "Hücumdan sonra on–on beş dəqiqəlik interval",
              kk: "Шабуылдан кейін оннан он бес минутқа дейінгі аралық",
            },
            B: {
              uk: "Проміжок часу від сорока п’яти до шістдесяти хвилин після вибуху",
              en: "A period of forty-five to sixty minutes after the blast",
              de: "Ein Zeitraum von fünfundvierzig bis sechzig Minuten nach der Explosion",
              es: "Un periodo de cuarenta y cinco a sesenta minutos después de la explosión",
              fr: "Une période de quarante-cinq à soixante minutes après l’explosion",
              az: "Partlayışdan sonra qırx beş–altmış dəqiqəlik müddət",
              kk: "Жарылыстан кейін қырық бес-алпыс минуттық кезең",
            },
            C: {
              uk: "Період тривалістю від двох до чотирьох хвилин від моменту влучання",
              en: "A period of two to four minutes from the moment of impact",
              de: "Ein Zeitraum von zwei bis vier Minuten ab dem Einschlag",
              es: "Un periodo de dos a cuatro minutos desde el momento del impacto",
              fr: "Une période de deux à quatre minutes à partir du moment de l’impact",
              az: "Dəymə anından iki–dörd dəqiqəlik müddət",
              kk: "Түсу сәтінен екі-төрт минуттық кезең",
            },
          },
          correct: "A",
        },
        {
          id: 9,
          question: {
            uk: "На яку мінімальну дистанцію від місця першого влучання необхідно відійти для безпеки?",
            en: "What minimum distance from the first impact site should you move away for safety?",
            de: "Welche Mindestentfernung vom ersten Einschlagsort sollten Sie aus Sicherheitsgründen einhalten?",
            es: "¿A qué distancia mínima del lugar del primer impacto debe alejarse por seguridad?",
            fr: "À quelle distance minimale du premier point d’impact devez-vous vous éloigner pour votre sécurité ?",
            az: "Təhlükəsizlik üçün birinci dəymə yerindən minimum hansı məsafəyə uzaqlaşmaq lazımdır?",
            kk: "Қауіпсіздік үшін бірінші соққы орнынан минималды қандай қашықтыққа шегіну керек?",
          },
          options: {
            A: {
              uk: "Відстань від сорока до сімдесяти метрів",
              en: "A distance of forty to seventy meters",
              de: "Eine Entfernung von vierzig bis siebzig Metern",
              es: "Una distancia de cuarenta a setenta metros",
              fr: "Une distance de quarante à soixante-dix mètres",
              az: "Qırx–yetmiş metr məsafə",
              kk: "Қырықтан жетпіс метрге дейінгі қашықтық",
            },
            B: {
              uk: "Відстань від ста до двохсот метрів укриття",
              en: "A distance of one hundred to two hundred meters to shelter",
              de: "Eine Entfernung von einhundert bis zweihundert Metern zur Deckung",
              es: "Una distancia de cien a doscientos metros hasta un refugio",
              fr: "Une distance de cent à deux cents mètres jusqu’à un abri",
              az: "Sığınacağa yüz–iki yüz metr məsafə",
              kk: "Баспанаға жүзден екі жүз метрге дейінгі қашықтық",
            },
            C: {
              uk: "Відстань від чотирьохсот до шестисот метрів",
              en: "A distance of four hundred to six hundred meters",
              de: "Eine Entfernung von vierhundert bis sechshundert Metern",
              es: "Una distancia de cuatrocientos a seiscientos metros",
              fr: "Une distance de quatre cents à six cents mètres",
              az: "Dörd yüz–altı yüz metr məsafə",
              kk: "Төрт жүзден алты жүз метрге дейінгі қашықтық",
            },
          },
          correct: "B",
        },
        {
          id: 10,
          question: {
            uk: "Чому категорично заборонено публікувати в мережі фото та відеоматеріали з місць прильотів?",
            en: "Why is it strictly forbidden to post photos and videos from impact sites online?",
            de: "Warum ist es streng verboten, Fotos und Videos von Einschlagsorten online zu veröffentlichen?",
            es: "¿Por qué está estrictamente prohibido publicar en línea fotos y vídeos de los lugares de impacto?",
            fr: "Pourquoi est-il strictement interdit de publier en ligne des photos et vidéos des sites d’impact ?",
            az: "Niyə dəymə yerlərindən foto və video materialları şəbəkədə paylaşmaq qəti qadağandır?",
            kk: "Неге соққы орындарынан фото мен бейне материалдарды желіге жариялау қатаң тыйым салынған?",
          },
          options: {
            A: {
              uk: "Це провокує миттєве перевантаження базових станцій мобільного зв’язку",
              en: "It instantly overloads mobile base stations",
              de: "Es überlastet sofort die Mobilfunk-Basisstationen",
              es: "Sobrecarga al instante las estaciones base de telefonía móvil",
              fr: "Cela surcharge instantanément les stations de base mobiles",
              az: "Bu, mobil rabitə baza stansiyalarını dərhal həddən artıq yükləyir",
              kk: "Бұл ұялы байланыс базалық станцияларын бірден шамадан тыс жүктейді",
            },
            B: {
              uk: "Це порушує юридичні авторські права операторів відеофіксації подій",
              en: "It violates the copyright of operators filming the events",
              de: "Es verletzt das Urheberrecht der Personen, die die Ereignisse filmen",
              es: "Viola los derechos de autor de quienes filman los hechos",
              fr: "Cela viole les droits d’auteur des opérateurs filmant les événements",
              az: "Bu, hadisələri çəkən operatorların müəllif hüquqlarını pozur",
              kk: "Бұл оқиғаларды түсіретін операторлардың авторлық құқығын бұзады",
            },
            C: {
              uk: "Це дозволяє аналітикам ворога встановити координати для другого дрона",
              en: "It lets enemy analysts establish coordinates for a second drone",
              de: "Es ermöglicht feindlichen Analysten, Koordinaten für eine zweite Drohne zu ermitteln",
              es: "Permite a los analistas enemigos establecer coordenadas para un segundo dron",
              fr: "Cela permet aux analystes ennemis d’établir des coordonnées pour un second drone",
              az: "Bu, düşmən analitiklərinə ikinci dron üçün koordinatları müəyyən etməyə imkan verir",
              kk: "Бұл жау аналитиктеріне екінші дрон үшін координаттарды анықтауға мүмкіндік береді",
            },
          },
          correct: "C",
        },
      ],
    },
  ],
};
